### ISSUE TITLE
ISIC2017 data issues

### ISSUE THREAD

**Issue by JianJianYin** [rezazad68/TMUnet#14]
It was a pleasure to read your work and I have a question. I observed that your ISIC2017 data division is to divide the training set of 2000 images into 1400 training images, 200 validation and 400 testing, but shouldn't the usual division be 2000 training set, 150 validation and 600 testing, I look forward to your reply.

**Comment by moeinheidari** [comment]
Hi Jian. Thanks for your interest in our work. Following the literature work, as mentioned in the paper, for each
series, we divide the dataset into train, validation, and test sets accordingly.

**Comment by moeinheidari** [comment]
Hi Jian. Thanks for your interest in our work. Following the literature work, as mentioned in the paper, for each
series, we divide the dataset into train, validation, and test sets accordingly.
