### ISSUE TITLE
Multiple Myeloma Cell Segmentation codes

### ISSUE THREAD

**Issue by alibalapour** [rezazad68/TMUnet#3]
Hi.
Can you share codes and notebooks of the Multiple Myeloma Cell Segmentation task?

**Comment by moeinheidari** [comment]
Hi.
As mentioned in the paper we've followed a constant pipeline for this task. We refer the following repository for the pipeline of training the Multiple Myeloma Cell Segmentation task. All you need to do is to change the model to use our method.
Referred repo : https://github.com/bmdeep/SegPC2021
