### ISSUE TITLE
FileNotFoundError when running ISIC2018 demo

### ISSUE THREAD

**Issue by alibalapour** [rezazad68/TMUnet#5]
I want to run the demo on the ISIC2018 dataset. I do what you said in the Readme, but in the third stage, when I run `train_skin.py`, this error has occurred:
```
Traceback (most recent call last):
  File "train_skin.py", line 36, in <module>
    train_dataset = isic_loader(path_Data = data_path, train = True)
  File "/kaggle/working/TMUnet/loader.py", line 44, in __init__
    self.data   = np.load(path_Data+'data_train.npy')
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './processed_data/isic18/data_train.npy'
```
I think this is because in the Prepare_ISIC2018.py you didn't give the path correctly. Because `data_train.npy`, `mask_train.npy`, and other generated npy files are in the main directory.

**Comment by moeinheidari** [comment]
Dear alibalapour, Thanks for your inquiry. You can manually specify the path through the dataset files in the code. This will definitely solve the problem.
