### ISSUE TITLE
About the boudary loss

### ISSUE THREAD

**Issue by GuoQingqing** [rezazad68/TMUnet#7]
Hi,
you have done a splendid work and thanks for your code. I have a question about the boudary loss.  In your code,  the boudary loss did not use the boundary, `loss_boundary = criteria(msk_pred, msk)`. And I run the code , I found the extracted  boudary  by the function "def Bextraction (img)" is not the edge. As shown below:
![1](https://user-images.githubusercontent.com/34561362/159225738-a8a14fc2-f36d-4db6-979a-2112f4a80e0b.png)

It would be very kind of you to answer my question.
Thanks.

**Comment by rezazad68** [comment]
Many thanks for your interest in our work. I have revised the boundary loss section and updated the code. Thanks for your precise issue.
