### ISSUE TITLE
loss_regions = nan

### ISSUE THREAD

**Issue by long123524** [rezazad68/TMUnet#8]
![image](https://user-images.githubusercontent.com/73996375/160860298-ed8c189f-c809-4a8d-9e43-24d0ea66ade8.png)
Very good job. I have a question, my loss is a nan value, as in the figure above, is there any solution？

**Comment by jack0012345678** [comment]
![image](https://user-images.githubusercontent.com/75615507/167688115-0515b88c-fefc-48a7-b559-4d3532b1aff5.png)
I slove this problem!(28~31)

**Comment by moeinheidari** [comment]
Thanks for your interest!
