### ISSUE TITLE
Training with ISIC2017 dataset and getting this results. Can you figure it out what's the issue?

### ISSUE THREAD

**Issue by Sharifmhamza** [rezazad68/TMUnet#9]
![thesis](https://user-images.githubusercontent.com/32780776/166085419-aabca7c0-2ad0-4846-a10a-c4f42979ca51.png)

**Comment by moeinheidari** [comment]
Dear Hamza Sharif. I tested the code again and there was no problem in training the model. However, for further information regarding the "nan" problem of the loss function, I refer you to https://stackoverflow.com/questions/40050397/deep-learning-nan-loss-reasons
